SLAP =  ["{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    r"( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!", 
    "Shut up {user2}, you are just {user2}.",  
    "{user1} hits {user2} with Aka si anse!",
    "@NeoTheKitty scratches {user2}",
    "Majin buu ate {user2}",
    "Goblin slayer slays {user2}"]

ABUSE = ["Your nasty behaviour is the reason for your receding hairline.",
"Silence is the best answer for a fool",
"If you could smell you, you wouldn’t be friends with you.",
"Being friends with you is only useful if I’m looking for a Slave",
"Serial killers would run mad if they tried to make you a victim.",
"You are the only friend in our group who’s going to hell",
"Your writing is not made for this chat you Fool!",
"Talking to you is like stepping on a leaf in autumn and hearing no crunch- disappointment.",
"Taking a picture of you would put a virus on my phone",
"No one noticed when you left; that’s how insignificant you are",
"having you as a friend looks like a bad dream:(",
"I’d be happy to hear from you if you were actually important. but looks like your talk is stupid as always:|",
"Your mother should’ve swallowed you",
"If I typed ‘stupid’ in google, your name would pop up",
"I can’t insult you. The universe has already helped by making you look like that",
"You deserve to be loved from a distance",
"One day god wanned to make a dumb person then god made you!",
"You are as annoying as the crying baby on the plane",
"If a cannibal wanted to eat you, he wouldn’t find anything in your brain",
"The mirror broke when you looked at it. FIX YOUR STUPID FACE!!!",
"I think we might celebrate your birthday on 1st April. you know why cuz that day was specially made for fools like you",
"Remember, if anyone says you’re beautiful, it’s all lies",
"Roses are red; violets are blue. You a fool, and that will always be true",
"For you, a fool at 40, remains a fool forever.",
"All your brain is in that suitcase",
"I’m jealous of how you can be so dumb",
"You are alone in this. I don’t support foolish behaviour",
"How can your IQ be in single numbers",
"Your mouth should be as silent as the ‘p’ in psychology",
"I wonder how do you show your stupid face on public place?",
"I beleive that god won't make mistake. but i see now that god really made a mistake to make a peraon like you",
"I was thinking you are a bad person. but now i see its true",
"WoW! Finally i saw a person with Zero good habits",
"Looks like donkeys are better then you",
"You should try playing snake and ladders, with real snakes and no ladders.",
"Don't drink and type.",
"Are you crazy you fool.",
"What language are you speaking? Cause it sounds like bullshit.",
"You should try holding TNT in your mouth and igniting it.",
"Your IQ's lower than your shoe size.",
"Launch yourself into outer space while forgetting oxygen on Earth.",
"I would ask you how old you are but I know you can't count that high."
"I don't know what makes you so stupid, but it really works.",
"Ordinarily people live and learn. You just live.",
"Try provoking a tiger while you both are in a cage.",
"Have you tried shooting yourself as high as 100m using a canon.",
"Stupidity is not a crime so you are free to go.",
"give your 100%. Now, go donate blood.",
"Go Green! Stop inhaling Oxygen.",
"Do you realize you are making a fool of yourself? Apparently not.",
"I think you should go home or better a mental asylum.",
"You should try sleeping forever.",
"Your enzymes are meant to digest rat poison.",
"You didn't evolve from apes, they evolved from you.",
"Owww ... Such a stupid idiot.",
"Active Volcano is the best swimming pool for you.",
"You should try hot bath in a volcano.",
"Alas! Your neurotransmitters are no more working.",
"Volunteer for target in an firing range.",
"Brains aren't everything. In your case they're nothing.",
"Head shots are fun. Get yourself one.",
"Shock me, say something intelligent.",
"Believe me you are not normal.",
"You are proof that evolution CAN go in reverse.",
"God was searching for you. You should leave to meet him.",
"You Noob!!",
"You should try swimming with great white sharks.",
"Stop talking BS and jump in front of a running bullet train.",
"I'm not saying you're stupid, I'm just saying you've got bad luck when it comes to thinking.",
"Hit Uranium with a slow moving neutron in your presence. It will be a worthwhile experience.",
"Try this: if you hold your breath underwater for an hour, you can then hold it forever.",
"You can stay underwater for the rest of your life without coming back up.",
"Try bathing with Hydrochloric Acid instead of water.",
"Everyone has the right to be stupid but you are abusing the privilege.",
"You should paint yourself red and run in a bull marathon."]

DECIDE = ["Yes.","Maybe.","No.","Maybe Not."]

PAT = ["{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ"]
    
WEEBIFY = [
    "卂",
    "乃",
    "匚",
    "刀",
    "乇",
    "下",
    "厶",
    "卄",
    "工",
    "丁",
    "长",
    "乚",
    "从",
    "𠘨",
    "口",
    "尸",
    "㔿",
    "尺",
    "丂",
    "丅",
    "凵",
    "リ",
    "山",
    "乂",
    "丫",
    "乙",
]

ITEMS = [
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
]

THROW = [
    "throws",
    "flings",
    "chucks",
    "hurls",
]

HIT = [
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
]

GIFS = ["https://telegra.ph/file/b5fae1e81c0d8774a6bde.gif",
"https://telegra.ph/file/c43ea24473781511d8d38.gif",
"https://telegra.ph/file/7302816408215c019cce7.gif",
"https://telegra.ph/file/c58cab9cb87433ce1cdea.gif",
"https://telegra.ph/file/abfcf98ff55f1ab5ba867.gif",
"https://telegra.ph/file/9d29332cf6d314af75f35.gif",
"https://telegra.ph/file/d1bec3ad02b82d5d0bef7.gif",
"https://telegra.ph/file/6d54871ce1630ca0c51a7.gif",
"https://telegra.ph/file/8ebf8d76ce141edde1439.gif",
"https://telegra.ph/file/44b30f9b0367c86f728a7.gif",
"https://telegra.ph/file/7a04d258720a17f0ff647.gif",
"https://telegra.ph/file/017a3f7661daf1a1950b3.gif",
"https://telegra.ph/file/2838c7f026e085de92259.gif",
"https://telegra.ph/file/7975ea994a76649ce2b8b.gif",
"https://telegra.ph/file/c5800c4f21c2fb3aca67e.gif",
"https://telegra.ph/file/16dc6c12430fd9baea956.gif",
"https://telegra.ph/file/0e9ec32cedf1e5cd0b077.gif",
"https://telegra.ph/file/d8ef3df72a71fced1410e.gif",
"https://telegra.ph/file/e058781dfcce5ac109213.gif",
"https://telegra.ph/file/624c91f2f44c9539cedbf.gif",
"https://telegra.ph/file/d0bb055779da6ed7de640.gif",
"https://telegra.ph/file/74410497dac5f8b519a15.gif",
"https://telegra.ph/file/79d9193c88d64830b1bb0.gif",
"https://telegra.ph/file/46686db9d0bff8d7da666.gif",
"https://telegra.ph/file/65e298e3b5eb415e1cf4d.gif",
"https://telegra.ph/file/694f8fd5d9181ee2f13d6.gif",
"https://telegra.ph/file/a65fbbb1fbcc02af2ce66.gif",
"https://telegra.ph/file/dbdc29e6e37d34684454f.gif",
"https://telegra.ph/file/f6fd2f0860a992f5f9b16.gif",
"https://telegra.ph/file/c5be9617905210f2efa01.gif",
"https://telegra.ph/file/66e517d26482da66c1771.gif",
"https://telegra.ph/file/1bc90d17f9b9d5662cdab.gif",
"https://telegra.ph/file/6f7cb1e33a20aff5a5e80.gif",
"https://telegra.ph/file/4c67599a75e828d905264.gif",
"https://telegra.ph/file/5601415b4413c5d7d0f5c.gif",
"https://telegra.ph/file/695d553f39a4b19b9f1cd.gif",
"https://telegra.ph/file/de02ff37bd5733af08059.gif",
"https://telegra.ph/file/2cd4aa83ff04f0f824e4e.gif",
"https://telegra.ph/file/639e4a3ef4c0c40265041.gif",
"https://telegra.ph/file/df9e246afd7bdb586aba1.gif",
"https://telegra.ph/file/5f96c2b476293b4f159a1.gif",
"https://telegra.ph/file/8cf01be88002f2aaa8da8.gif",
"https://telegra.ph/file/c551366ecdf7070c477b4.gif",
"https://telegra.ph/file/b77163434e55547112336.gif",
"https://telegra.ph/file/6037614dd15067401e449.gif",
"https://telegra.ph/file/8ef07fec1c64adb567d2e.gif",
"https://telegra.ph/file/2d4118441f8447c5e3b40.gif",
"https://telegra.ph/file/9d092222393eba57f9e92.gif",
"https://telegra.ph/file/1601e0a0c87df8d45898e.gif",
"https://telegra.ph/file/f7652ff75e2420bb308d8.gif",
"https://telegra.ph/file/072450d2ce541cf23da8d.gif",
"https://telegra.ph/file/99062513e5936a7dd153b.gif",
"https://telegra.ph/file/91552cccf1f3244e5ba01.gif",
"https://telegra.ph/file/6b6c634f06edc91022fa1.gif",
"https://telegra.ph/file/6abc6ba578cb8e5bb589b.gif",
"https://telegra.ph/file/07590548cabd9e58c133c.gif",
"https://telegra.ph/file/38577cf9d501d2893f3a9.gif",
"https://telegra.ph/file/c7a82253dc467eaf1f062.gif",
"https://telegra.ph/file/144db7bdb64f268844893.gif",
"https://telegra.ph/file/ab3945c4bb8e7c2158ed7.gif",
"https://telegra.ph/file/01600747a54930bd77f4a.gif",
"https://telegra.ph/file/d75903f5e09f9862660d4.gif",
"https://telegra.ph/file/8b85e80c9216864309144.gif",
"https://telegra.ph/file/92efab70a0f9795a515ff.gif",
"https://telegra.ph/file/ca1ef0d182726de305203.gif",
"https://telegra.ph/file/352bcbefc9cd3bfc73252.gif",
"https://telegra.ph/file/484aa38cb4bc00d0a2871.gif",
"https://telegra.ph/file/a8aadd106219c85a95d55.gif",
"https://telegra.ph/file/9649b4054abb662955e02.gif",
"https://telegra.ph/file/1e06665d155b3e21d6c79.gif",
"https://telegra.ph/file/f4955f44690d7e7d7219b.gif",
"https://telegra.ph/file/81194df400b1b2863cdf7.gif",
"https://telegra.ph/file/62e6f9fc7f4878270353e.gif",
"https://telegra.ph/file/f46dbcfc7ce1927ceccb2.gi",
"https://telegra.ph/file/64392d782a42879d9f75c.gif",
"https://telegra.ph/file/eea65334bb9d58488d2f7.gif"]