
TRUTH = [
"Have you ever eaten your own boogers?",
"What’s the longest you’ve gone without showering?",
"What’s the longest you’ve gone without brushing your teeth?",
"Who would you hate to see naked?",
"If you woke up as the opposite sex for one day, what would you do?",
"Have you ever faked being sick to avoid a commitment like school or work?",
"Have you ever walked in on someone else having sex?",
"Has anyone ever walked in on you having sex?",
"Describe the weirdest date you’ve been on.",
"When’s the last time you ever wet the bed?",
"What’s the funniest thing you’ve ever witnessed in person?",
"Tell us about a hookup you would rather forget happened.",
"Have you ever stolen something? What was your strategy?",
"What was the weirdest thing you ever ate but pretended to enjoy?",
"What’s the strangest dream you’ve ever had?",
"Admit your worst fart story.",
"Have you ever peed in a pool?",
"Tell your worst hangover story.",
"Would you rather date someone 20 years older or 20 years younger, and why?",
"Did you have an imaginary friend when you were a child? What were they like?",
"Have you ever practiced kissing in a mirror?",
"What celebrity would you want to get trapped on an island with?",
"What’s the largest amount of food you’ve eaten all at once?",
"Out of everyone in the room, who would you pick to trade lives with for a day?",
"Have you ever purposely made someone cry? Tell us your motives.",
"What’s the awkwardest thing that’s happened to you when hooking up with someone?",
"Did you sleep in your parent’s bed growing up? How old were you when you stopped?",
"What’s the most embarrassing thing you’ve done to impress a crush?",
"What do you think about while sitting on the toilet?",
"Has anyone accidentally seen you naked? Tell us the details.",
"Have you ever sent a text message to the wrong person? What did it say?",
"What’s your most embarrassing habit?",
"Have you ever had a major wardrobe malfunction in public?",
"If you could read minds, how would you use the gift?",
"Have you ever farted and blamed someone else?",
"Have you ever accidentally walked into the wrong bathroom?",
"Do you pick your nose when you’re alone?",
"Do you pee in the shower?",
"Have you ever peed your pants in public?",
"Do you sleep with a stuffed animal at night?",
"Who is the strangest person you’ve pleasured yourself to?",
"Have you ever tasted earwax?",
"How often do you change your sheets?",
"How often do you wash your underwear?",
"What’s the worst pick up line you’ve used while trying to attract someone’s attention.",
"Do you smell your farts?",
"What’s the strangest nickname you’ve ever been given?",
"If you had to make out with a Disney character, who would you pick?",
"What’s the cringiest trend you’ve participated in?",
"Have you ever pooped yourself?",
"What “As Seen on TV” product do you secretly want to buy or have bought?",
"Who’s the hottest person you’ve ever slept with?",
"Who was your first kiss?"
"Have you ever taken someone’s virginity?",
"Who took your virginity?",
"If you had to make out with someone in this room, who would it be?",
"Who are you most attracted to in this room?",
"Where is the strangest place you’ve ever had sex?",
"Do you have any sexual fantasies?",
"Tell us about a time you actually used a pickup line.",
"What’s the kinkiest thing you’ve ever tried in bed?",
"Have you ever slept with a random person?",
"How many people have you slept with?",
"Does body count matter to you? Why or why not?",
"What’s something you want to try in bed?",
"What’s your favorite position?",
"How old were you when you lost your virginity?",
"Would you rather date someone older or younger than you?",
"What’s a common fetish that you never want to try?",
"What’s a popular sex position that you hate?",
"What do you find most attractive about the other sex?",
"What do you find most attractive about the same sex?",
"Have you ever lied to someone just to get them to sleep with you?",
"Would you rather receive oral sex or have full-on sex?",
"If you were able to have one sexual superpower, what would you choose?",
"If you could, would you sleep with your supervisor?",
"What’s your body count?",
"How many is “too many” people to have sex with?",
"If you were to have a threesome, would you want the third party to be of the opposite sex or the same sex?",
"Have you ever cheated on your boyfriend or girlfriend?",
"What’s the least amount of time you’ve gone between sleeping with people?",
"What’s the greatest amount of people you’ve kissed in one day?",
"What’s the greatest amount of people you’ve slept with in one day?",
"Have you ever been caught having sex?",
"What animated character do you think is hot?",
"Who is the strangest person you’ve been sexually attracted to?",
"Do you feel that your virginity is special?",
"Do you prefer sex when it’s a hot hookup or when you’re in love with someone?",
"What’s the shortest amount of time you’ve known someone before sleeping with them?",
"What age do you think is “too old” for someone to be a virgin still?",
"Who in the room do you think has slept with the most people?",
"Who in the room do you think is secretly kinky?",
"Have you ever slept with someone and then immediately left after or asked them to leave?",
"Have you ever called someone “daddy” or been called “daddy” in bed?",
"What advice do you wish you had gotten about sex way earlier than you did?",
"If you had to pick a Disney character to sleep with, who would it be?",
"Have you ever had a crush on a friend‘s parent?",
"How old were you the first time you experienced sexual feelings?",
"How old were you the first time you discovered porn?",
"What’s the biggest age gap you could have when dating someone?",
"Tell us a story about the stupidest thing you’ve ever done while drunk.",
"Did you ever sneak out of the house when you were younger?",
"Did you drink before you reached the legal drinking age?",
"Have you ever done drugs?",
"What’s your guilty pleasure?",
"What is your most embarrassing habit?",
"If you could change one thing about yourself, what would it be?",
"Have you ever accidentally walked into a wall?",
"Do you talk to yourself sometimes?",
"Is there anything in your web history you would be embarrassed about someone seeing?",
"Do you have any weird habits when you sleep?",
"Do you have a type?",
"Who is your celebrity crush?",
"What’s the biggest lie you’ve ever told?",
"Out of the people you have dated, who were you most attracted to?",
"Who gave you your biggest heartbreak?",
"What’s your all-time favorite song to jam out to?",
"How would you rate your appearance on a scale of 1-10?",
"Do you think that you and your current partner will ever get married?",
"What’s the most illegal thing you’ve ever done?",
"Who is your favorite family member?",
"Would you ever join the military?",
"What is your biggest weakness?",
"What is your biggest strength?",
"What is your biggest pet peeve?",
"If you were allowed to marry more than one person, would you?",
"What’s your favorite TV show?",
"What’s your favorite game to play?",
"If you were to have a superpower, which would you choose?",
"How much do you value money?",
"If you could only be one, would you rather be successful or beautiful?",
"How do you envision success?",
"What’s your dream job?",
"What’s your biggest fear?",
"Do you have any phobias?",
"What’s your drink of choice?",
"Tell us about the drunkest you’ve ever been.",
"Who do you like more, your mom or your dad?",
"What’s your biggest regret?",
"Have you ever regretted posting something on social media?",
"What has been your proudest moment in life so far?",
"What day was the happiest of your life so far?",
"If you could go to dinner with any three people in history, dead or alive, who would you pick?",
"If you could relive a year of your life, which would you pick?",
"If you were going to die tomorrow, how would you spend today?",
"If you won a million dollars, what’s the first thing you would spend it on?",
"If you had the option of knowing when you would die and how, would you want to know? Why or why not?",
"What children’s movies do you still enjoy?",
"Have you ever been in a car accident?",
"Which phone app do you spend the most time on?",
"What’s the most painful injury you’ve ever gotten?",
"What’s the meanest thing you’ve ever said to someone?",
"How would you spend a day home alone?",
"Do you save things you cherished as a child?",
"If your house was on fire and you had the time to take one thing with you before you leave, what would you grab?",
"Are you an early bird or a night owl?",
"Have you ever had lice?",
"What is your favorite flavor of ice cream?",
"What’s your favorite type of food?",
"What’s your death row meal?",
"Who is your biggest role model?",
"Who is your favorite person to spend time with?",
"Have you ever had a crush on one of your teachers?",
"Where are you, ticklish?",
"What do you think is your best physical feature?",
"Have you ever cheated on a test in school?",
"Who is your guy celebrity crush?",
"Who is your girl celebrity crush?",
"Are you superstitious?",
"Do you believe in karma?",
"Do you believe in a higher power?",
"Do you believe in love at first sight?",
"Do you believe in fate?",
"Where is the coolest place you’ve ever traveled to?",
"What’s the strangest food combination you love?",
"What movie never fails to make you cry?",
"Have you ever been arrested or almost been arrested?",
"If you were famous, what would you want it to be for?",
"What’s your biggest insecurity?",
"What do you feel passionate about?",
"What cause do you feel extremely tied to?",
"If you were to donate to a charity, which would you donate to?",
"Have you ever pulled a prank on someone? Tell the group about it.",
"Who is your least favorite family member?",
"Have you ever lied on your resume?",
"What is an instant deal-breaker for you in a new relationship?",
"Have you ever been in a fight?",
"When you’re home alone, do you walk around nude?",
"Where is the worst place you’ve ever thrown up?",
"What’s the worst thing you’ve ever eaten?",
"Which is worse, physical pain or emotional pain?",
"What destination is on your travel bucket list?",
"Describe your dream date.",
"What word do you hate hearing?",
"If you could switch bodies with anyone who would you choose?",
"What’s the worst rumor you’ve ever started or perpetuated about someone?",
"Have you ever been fired?",
"Who is the best kisser you’ve ever kissed?",
"Have you ever met a famous person?",
"What’s a skill you wish you were better at?",
"Have you ever had your life flash before your eyes?",
"Do you ever think there’s an excuse for cheating?",
"Would you ever consider being in an open relationship?",
"Have you ever compromised your morals for money?",
"Have you ever cried by reading a book?",
"What’s the best book you’ve ever read?",
"What would be the worst way to die?",
"What’s your favorite movie ever?",
"Have you ever broken someone’s heart?",
"How do you think other people see you?",
"Who in the group gave you the worst first impression? Describe it.",
"Have you ever compromised your morals for someone you love?",
"What legacy do you want to leave behind?",
"What’s your spirit animal?",
"Tell us a story about the most scared you’ve ever been.",
"If you had to get a tattoo, what would it be of?",
"Do you believe in astrology?",
"What’s the longest distance you’ve ever run?",
"What’s the best piece of advice you’ve ever received?",
"What’s the best lesson for a child to learn?",
"What’s something you wish you knew as a child that you know now?",
"What’s the worst hairstyle you’ve ever sported?",
"Do you believe in aliens?",
"Do you believe in ghosts?",
"Have you ever said “I love you” and didn’t actually mean it?",
"What’s the worst advice you’ve ever taken?",
"Are you more of an introvert or an extrovert?",
"How many children do you want to have one day?",
"Are you competitive?",
"Do you look at your poop before you flush the toilet?",
"Have you ever sought revenge?",
"What’s your least favorite memory?",
"What’s your favorite holiday, and why?",
"When’s the last time you internet stalked someone?",
"What hobby would you love to take up?",
"What’s your strangest obsession or pastime?",
"What’s your favorite candy?",
"Are you afraid of death?",
"Who has the best butt in the room?",
"What’s something you hold guilt over in your life?",
"What’s your biggest turn on?",
"What’s the biggest change you’ve ever gone through in life?",
"What’s one of the hardest lessons you had to learn in life?",
"What was your childhood nickname?",
"What’s the worst present you’ve ever received?",
"What’s the best present you’ve ever given?",
"What’s the most attractive quality someone can have?",
"What’s your biggest turn-off?",
"Have you ever had an STI?",
"Have you ever drank so much you don’t remember the night?",
"Have you ever thrown up on someone else?",
"If you had to, what would you get plastic surgery for?"
]

DARE = [
"Put an ice cube down your pants until your next turn.",
"Eat a spoonful of mayonnaise.",
"Show us the last photo on your phone.",
"Until your next turn, speak in your best British accent.",
"Fill your mouth with water and recite the ABC’s.",
"Pretend to make out with a pillow.",
"Burp the alphabet as best you can.",
"Perform your best belly dance.",
"Do a naked lap around your backyard.",
"Write your name on the floor with your tongue.",
"Go on a social media app and the first account you see, click on them, and like as many photos of theirs as you can for 30 seconds.",
"Try to eat a whole piece of paper.",
"Let the group choose something you must attempt to brush your teeth with.",
"Yell something crazy really loud outside of your house.",
"Lick a car tire.",
"Imitate someone in the room and don’t stop until the group guesses who it is.",
"Lick someone’s foot.",
"Imitate your best farting noises in front of the group.",
"Let the group draw something on your face with a pen.",
"Do a show and tell with the contents of your purse or wallet.",
"Text the first 5 people in your contact list a random emoji.",
"Lick a bar of soap.",
"Smell everyone’s breath in the room and rank them best to worst.",
"Jump into a dumpster or trash can.",
"Lift the couch cushions and if there’s any food, place it in your mouth for 10 seconds.",
"Let the rest of the group DM or message someone on your preferred social media app.",
"Play “Chubby Bunny” in front of the group.",
"Eat a raw piece of garlic.",
"Eat a piece of raw onion.",
"Eat a raw egg.",
"Do your best twerking in front of the group for 30 seconds.",
"Try your best to lick your elbow.",
"Spin around 10 times and try to walk in a straight line.",
"Shave off part of your eyebrow.",
"Dye part of your hair a crazy color.",
"Rub your hands under your armpits and then smell them.",
"Let the group make a concoction out of things in the refrigerator and rub it on your face.",
"Close your eyes and try to guess 5 foods that the group pulls from the kitchen.",
"Dress up as the opposite sex and imitate them.",
"Wear your underwear on your head for the rest of the game.",
"Let your friends pose you a certain way and stay like that until your next turn.",
"Trade socks with the player that’s to the right of you.",
"Read through the first note you have on your phone.",
"Have someone in the group put a leash on you and walk you around like you’re an animal.",
"Wear the person across from you’s socks as if they’re gloves until your next turn.",
"Perform a small concert of the song of your choice with props and everything.",
"Let the person to your left gift you a wedgie.",
"Pretend like you’re a dog until your next turn.",
"Create a short song about the party host and perform it for the group.",
"Ding dong ditch your neighbor’s house.",
"Call your ex and leave a raunchy voicemail.",
"Spin a bottle and kiss who it lands on.",
"Pretend to make love to a piece of furniture in the room.",
"Dance on a broom as if you are a stripper.",
"Read an excerpt from a book in your sexiest voice.",
"Send a raunchy text to a contact that the group picks out of your contact list.",
"Message something bold to someone you think is hot.",
"Do your best fake orgasm in front of the group.",
"Do a naked lap around the neighborhood.",
"Do a mini striptease for the group.",
"Online, find a position that you’ve never tried and act it out for the group.",
"Prank call somebody and pretend to be a sex ad.",
"Pick a position and imitate it with the person to your right.",
"Trace the lips of the person next to you and whisper something sexy.",
"Place your hand on the inner thigh of the person to your left and keep it there until the end of the round.",
"Sit on the lap of the person to your right until the round is over.",
"Post a raunchy update on your preferred social media app, and don’t take it down until the round is over.",
"Give someone in the group a sexy massage while talking dirty to them.",
"If there’s water nearby, it’s time for skinny dipping!",
"Kiss the person in the room you’re most attracted to.",
"Eskimo kiss the person to your left.",
"Butterfly kiss the person to your right.",
"Sexily lick food off your finger in front of the group.",
"se an item from the kitchen and pretend to perform oral sex on it.",
"Sexily feed something to someone else in the group.",
"Have the members of the group stand in a line across from you. Close your eyes and walk with your hands open. Stop when you touch someone and kiss wherever your hand landed.",
"Fake your best blowjob on a bottle.",
"Wink and do your best sexy face for the group.",
"Dress up like the opposite sex and pretend to flirt like them for 20 seconds.",
"Talk in a raunchy accent until the next round is over.",
"Take a pen and paper and draw the most detailed penis or vagina you can.",
"Give your best impression of a naughty cop.",
"Leave the room while everyone else in the room pours a shot. When you come back into the room, pick a shot to take. Whoever poured the one you took, you have to kiss them.",
"Pretend to have horrible sex with the person to your right.",
"Send a dirty text message to someone you used to hookup with.",
"Scroll blindly through your contacts. Whoever you land on, say one thing that’s sexy about them.",
"Call a phone sex line and pretend to have a strange fetish you want them to cater to.",
"Play charades with your favorite position and furniture in the room to see if the group can guess what it is.",
"Describe your favorite position in detail and see if the group can guess what it is.",
"Motorboat someone or have someone motorboat you.",
"Act out 5 dirty emojis and see if the group can guess what they are.",
"Say something not sexy in a sexy voice.",
"Surrender your phone to the group and let them pick a song you have to dance to sexily.",
"Play a song for the group that you’ve had sex to before.",
"Draw something on the back of the person to your left. If they guess incorrectly, the punishment is to do something raunchy that the group decides on.",
"Give a lap dance to someone in the room.",
"Have someone in the group spank you with something from the kitchen.",
"If you’re a girl, take off your bra without taking off your shirt.",
"Wear your underwear on your head until the end of the next round.",
"Moon the group.",
"Hum your favorite song and see if the group can guess what it is.",
"Do your best touchdown dance.",
"Pour a glass of ice water on your head.",
"Time how long you can go without blinking.",
"Time how long you can go without taking a breath.",
"Let someone give you a wet willy.",
"Let someone teabag you.",
"Stick your hand in toilet water for 10 seconds.",
"Do the salt and ice challenge.",
"Lick your foot.",
"Act like a gymnast and do your best cartwheel performance for the group.",
"Show the group your most recently deleted photo.",
"Cut off some of your hair.",
"Let someone in the group tickle you for 30 seconds.",
"Try to bite into and chew a piece of gum with the wrapper still on.",
"Take a bite of an onion as if it’s an apple.",
"Write a poem about someone in the room and see if the group can guess who it is.",
"Put on makeup without looking in the mirror.",
"Take a bite out of a stick of butter.",
"Do the splits as best you can.",
"Lick the elbow of the person sitting on your left.",
"Post something on social media with a strange caption, and don’t delete it until your next turn.",
"Do the worm.",
"Try and moonwalk in front of the group.",
"Lick your armpit.",
"Let the player to your right, place your finger on a part of their body while your eyes are closed, then guess what you’re touching.",
"Eat a slice of lemon as if it was an orange slice.",
"Give the person to your right a foot massage.",
"Do sit-ups until your next turn.",
"Allow the players in the group to send a DM to one of your Instagram followers.",
"Make out with your hand.",
"Eat a dab of toothpaste.",
"Sing the alphabet backward. For each letter you get wrong, you must do a punishment that is chosen by the group.",
"Drink a mystery cocktail that the group creates.",
"Perform your best yodel.",
"Sensually lick the ear of the person sitting to your left.",
"Take a small bite out of chapstick.",
"Call a local place and ask them a stupid question about their menu.",
"Take a body shot off of someone else in the room.",
"Let someone in the group give you a makeover using only items from the fridge.",
"Do the classic spaghetti scene from Lady & the Tramp with another player in the room.",
"Draw a face on your stomach using your belly button as the mouth and talk as it until your next turn.",
"Let another player in the group rock you like a baby.",
"Chug a glass of milk.",
"Without using your hands, remove another player‘s sock.",
"Dance like a ballerina to music from The Nutcracker.",
"If you’re a girl, let the group play a round of boob-sketball with your cleavage as the basket.",
"Take a shower with your clothes on.",
"Go next door and try to sell something to the neighbor.",
"Give the player to your left a piggyback ride through the neighborhood.",
"Wear your pants backward until your next turn.",
"Eat a piece of dog or cat food.",
"Do your best handstand for the group.",
"Wall twerk for the group.",
"Come up with a dance routine and perform it for the group. You have one minute to rehearse.",
"Call your mom and convince her you’ve been arrested.",
"Call your mom and convince her you’re engaged.",
"Call your mom and tell her she’s going to be a grandma.",
"Talk in old English until your next turn.",
"Eat a piece of grass.",
"Have another member in the group use a piece of floss, then wear it as a necklace until the round is over.",
"Prank call the last person that called you.",
"Put your finger into the nose of another group member.",
"Put a pillow under your shirt and pretend to give birth.",
"Lick an unused tampon or pad.",
"Lick the floor.",
"Smell another group member’s armpit.",
"Pretend to seduce a stuffed animal.",
"Let other players turn you into a mummy using toilet paper and stay like that until the round is over.",
"Shave your arm.",
"Cut the toenails of another player.",
"Allow another player to punch you in the arm.",
"Allow another player to give you a titty twister.",
"Suck on your thumb until the round is over.",
"Eat a piece of food like an animal.",
"Place your hands into another player‘s pockets and keep them there until your next turn.",
"Lick a dollar bill.",
"Make your best impression of an animal of your choice.",
"Do the burnie dance until the round is over.",
"Brush another player‘s teeth using your finger.",
"Leave the house and try to take a selfie with a stranger.",
"Reenact your favorite scene from a movie until the group guesses which movie it is.",
"Try to cry on command.",
"Put a piece of cheese on your cheek until the round is over.",
"Wear your pants on your arms until your next turn.",
"Call a random number and express your deep love for the person on the other end. If they don’t answer, leave a voicemail.",
"Call a random number and have a conversation with them about their day.",
"Make your best impression of an auctioneer.",
"Change your profile picture to your worst photo until the game ends.",
"Take a shot of a condiment that the group chooses.",
"Try to touch your head with your feet.",
"Try to freestyle for the next minute.",
"Romantically dance with a broom or a mop for the next minute.",
"Do your best backbend.",
"Talk with a crazy accent until your next turn.",
"Do the chicken dance until the round is over.",
"Perform a dance craze from your childhood for the group.",
"Let another player spank you with a fly swatter.",
"Smother your face in peanut butter until your next turn.",
"Pour a glass of water without using your hands.",
"Tape two cups to the front of your shirt until your next turn.",
"Try to share a shirt with the person to your left.",
"Dance the Macarena in the sexiest way possible.",
"Go outside and do your best to sell ice to the people walking by.",
"Go outside, walk down the street and ask people what year it is as if you forgot.",
"Paint your fingernails with a crayon.",
"Connect with an old teacher on social media",
"Eat a spoonful of salt.",
"Read the last message you received aloud in a British accent.",
"Perform like a mime for the next minute.",
"Call a random number and sing them happy birthday.",
"Let someone in the group spank you with a fly swatter.",
"Make an impression of a celebrity until the group guesses who it is.",
"Open a window and try to get someone outside to wave back to you.",
"Have another player walk you outside like a dog.",
"Call your crush and just breathe deeply into the phone.",
"Try to hold a spoon on your nose until the round is over.",
"Take a round to learn a magic trick and then perform it for the group during your next turn.",
"Lick the food of your choice off the back of another player‘s neck.",
"Let the players pick 3 foods and feed them to you while you’re blindfolded. You must guess what they are.",
"Strike your best modeling poses for 20 seconds.",
"Act like a pig until the round is over.",
"Call the host “Your Majesty” until the game is over.",
"Kiss someone in the group that you’re attracted to on the forehead.",
"Play your best air guitar for 30 seconds like you’re performing a concert.",
"Cross your eyes as best as you can.",
"Flip your eyelids inside out.",
"Try to lick your nose.",
"Tell your best knock-knock joke to the group.",
"Close your eyes and have the group place 3 objects in your hands as you try to guess what they are.",
"Try to bench press the smallest person in the room.",
"Email an old professor and tell them you love them.",
"Take off your sock and bite it.",
"Eat a stereotypical pregnancy craving snack like a pickle with peanut butter.",
"Act like a human blanket and warm someone in the group up for the next round.",
"Imitate an older adult driving.",
"Ask your next-door neighbor for a banana and then wink.",
"Try to get a cookie from your forehead to your mouth for the next minute.",
"Hold an egg on a spoon in your mouth until your next turn.",
"Shotgun something.",
"Perform a nursery rhyme by rapping it.",
"Break an egg on your head.",
"Go pee outside.",
"Plank on random things in the room for the next minute.",
"Tie your hands to your ankles until the round is over.",
"Pick something out of the trash and make up a story about its journey.",
"Do a cannonball onto the couch.",
"Spin the bottle and whoever it lands on, take off their shirt with your teeth.",
"Sexily dance to a country song the group chooses.",
"Try to take a shot without using your hands."
]

TOSS = [
	"Heads",
    "Tales"
    ]

DICE = [
		"ONE (1)",
		"TWO (2)",
		"THREE (3)",
		"FOUR (4)",
		"FIVE (5)",
		"SIX (6)"
	]
